# =============================================================================
# log-functions.sh — Shared logging functions for all container scripts
#
# Provides consistent, timestamped log output across all services.
# Each script sets LOG_TAG before sourcing this file:
#
#   LOG_TAG="init-config"
#   . /usr/local/lib/log-functions.sh
#
# Output format: 2026-03-02T14:30:05+00:00 [init-config] message
# Error format:  2026-03-02T14:30:05+00:00 [init-config] ERROR: message
#
# Timestamps use ISO 8601 format with timezone, generated by BusyBox date.
# =============================================================================

# Guard: LOG_TAG must be set by the sourcing script
: "${LOG_TAG:?log-functions.sh: LOG_TAG must be set before sourcing}"

_log_timestamp() {
  date '+%Y-%m-%dT%H:%M:%S%z'
}

log() {
  printf '%s [%s] %s\n' "$(_log_timestamp)" "${LOG_TAG}" "$*"
}

log_error() {
  printf '%s [%s] ERROR: %s\n' "$(_log_timestamp)" "${LOG_TAG}" "$*" >&2
}

log_banner() {
  echo ""
  printf '%s [%s] ========================================\n' "$(_log_timestamp)" "${LOG_TAG}"
  printf '%s [%s]   %s\n' "$(_log_timestamp)" "${LOG_TAG}" "$*"
  printf '%s [%s] ========================================\n' "$(_log_timestamp)" "${LOG_TAG}"
  echo ""
}
