# =============================================================================
# log-functions.sh — Shared logging functions for all container scripts
#
# Provides consistent, timestamped log output across all services.
# Each script sets LOG_TAG before sourcing this file:
#
#   LOG_TAG="init-config"
#   . /usr/local/lib/log-functions.sh
#
# Output format: 2026-03-02T14:30:05Z [init-config] message
# Error format:  2026-03-02T14:30:05Z [init-config] ERROR: message
#
# Timestamps use ISO 8601 in UTC with a trailing Z, generated by
# BusyBox date. UTC is used because containers typically run in UTC
# and the Z suffix is unambiguous (no BusyBox %z formatting quirks).
#
# NOTE: `docker logs --timestamps` prepends a second timestamp.
# These embedded timestamps exist so logs are self-contained when
# viewed outside Docker (log files, log shippers, etc.).
# =============================================================================

# Guard: LOG_TAG must be set by the sourcing script.
# This is intentionally fatal (triggers immediate exit under set -e)
# to catch programming errors — all scripts must set LOG_TAG before
# sourcing this file.
: "${LOG_TAG:?log-functions.sh: LOG_TAG must be set before sourcing}"

_log_timestamp() {
  date -u '+%Y-%m-%dT%H:%M:%SZ'
}

log() {
  printf '%s [%s] %s\n' "$(_log_timestamp)" "${LOG_TAG}" "$*"
}

log_error() {
  printf '%s [%s] ERROR: %s\n' "$(_log_timestamp)" "${LOG_TAG}" "$*" >&2
}

# log_banner — visually prominent message for critical user-facing events.
# Timestamp is captured once so all lines in the banner share the same
# second, even if the shell is briefly delayed between printf calls.
log_banner() {
  _ts="$(_log_timestamp)"
  printf '%s [%s]\n'                                          "${_ts}" "${LOG_TAG}"
  printf '%s [%s] ========================================\n' "${_ts}" "${LOG_TAG}"
  printf '%s [%s]   %s\n'                                    "${_ts}" "${LOG_TAG}" "$*"
  printf '%s [%s] ========================================\n' "${_ts}" "${LOG_TAG}"
  printf '%s [%s]\n'                                          "${_ts}" "${LOG_TAG}"
}
